version: '3.8'

services:
  convocore-mcp:
    image: moe003/convocore-mcp:latest
    container_name: convocore-mcp-server
    environment:
      - CONVOCORE_API_KEY=${CONVOCORE_API_KEY}
      - WORKSPACE_SECRET=${WORKSPACE_SECRET}
      - CONVOCORE_API_REGION=${CONVOCORE_API_REGION:-eu-gcp}
    stdin_open: true
    tty: true
    restart: unless-stopped

